# Generated by Django 5.1.2 on 2024-10-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="password",
            field=models.CharField(default="default_password", max_length=16),
        ),
    ]
